# Generated by Django 3.2.13 on 2022-06-16 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accompaniment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chord_pitch', to='accompaniment.pitch', unique=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='album_cover',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
